### ISSUE TITLE
Time slider glitching and not displaying fully

### ISSUE THREAD

**Issue by mattster98** [andymchugh/andrewbmchugh-flow-panel#108]
I've noticed since I changed the time settings for my dashboard using Flow to "Browser time" from "UTC", the slider seems to glitch between the equivalent UTC time and the Browser time as I move it around.  It also seems to be trying to display data at the Browser time point-in-time resulting in other weirdness.  This glitching happens on the example SVG+YAML as well.

Additionally, the date+time display is getting cut-off at the bottom on mine.  I haven't been able to figure out why.  Resizing the visualization doesn't help.  It's almost like my SVG isn't wide enough and that's causing the wrapping of the date+time.

https://github.com/user-attachments/assets/03ae864d-eef4-4545-883b-543ba0f18469

**Comment by andymchugh** [comment]
Thanks for pointing out the timezone glitch. That's a bug that I'll get fixed in the next version.

Re the timeSlider label wrapping, that's a bit harder. it's not designed to wrap so the problem is the date/time doesn't have enough horizontal space. Can you give any details about your os, browser, etc. Does the problem go away if you copy paste the panel. Do you have the same wrapping problem on the example panel displayed initially?

**Comment by mattster98** [comment]
> Can you give any details about your os, browser, etc. 
Windows 11 Home, Chrome 128.0.6613.120 64-bit on a few year old Dell all-in-one (1080P display)

> Does the problem go away if you copy paste the panel. 
No, appears the same.

> Do you have the same wrapping problem on the example panel displayed initially?
No, the example seems fine.  

I tried to stretch out my SVG to be wider to see if my guess was correct and it had no effect.  I could stretch it very wide and skinny and it didn't affect the wrapping.  I also tried replacing my SVG with one from the example and it did not fix the wrapping, so I'm guessing maybe it's something to do with my YAML?

**Comment by mattster98** [comment]
I just realized I can fix it by turning off the "Animation Control Enabled" option.  That makes the play/pause icon go away which frees up the horizontal space in the slider section and removes the wrap on the date+time. 

Curiously, toggling that in the example doesn't make the play/pause show or not.. it's never there.

**Comment by mattster98** [comment]
The play/pause button doesn't seem to do anything either, but I'm not totally sure how it's supposed to work anyway.

**Comment by andymchugh** [comment]
The play/pause button is there if you have flowAnimation defined in your yaml and you have it enabled in the panel. As the initial example doesn't have it defined in yaml you don't see the button.

To actually see flowAnimations you need to enable them in draw.io on the particular connector and then export-as-svg rather than just save-as-svg. The export ensures the animation definition that draw.io has setup exists in the svg.

So if I'm understanding, the wrap problem has gone in your panel with the removal of the play/pause but still exists in the initial panel which doesn't have play/pause?

Do you happen to know your browser zoom setting, font and and font size too?

**Comment by mattster98** [comment]
I have flow animations configured in mine.  I see now what it actually does - I have always assumed it would cause the timeline to move as its position next to the timeline led me to think it would scroll through the data on some interval.

Toggling off the "Animation Control Enabled" makes the wrap problem go away on my panel.  I didn't see the wrap issue on the default example at all.

I switched to example 4 on a new visualization and turning on that toggle also causes the date+time to wrap.
![image](https://github.com/user-attachments/assets/10bd19ce-37c6-49f9-a77f-771ce9050db8)

I confirmed the browser zoom is 100%.  Display zoom and text size are both 100% in Windows.  Chrome font size is 16/Medium (Recommended).  Fonts all appear to be default.

**Comment by mattster98** [comment]
Just checked on mobile and it's happening there too. Having that option on makes the date+time wrap.

**Comment by andymchugh** [comment]
Thanks for info, realize this is caused by the AM/PM postamble. I'll correct the way it fits.

**Comment by andymchugh** [comment]
fix for this now on main and will be in the next release. The label glitch when non browser time is selected is now gone and the label positioning should now be fine regardless of whether a 12 or 24 hour format is selected and regardless of the animation play/pause button visibility.

**Comment by andymchugh** [comment]
this should now be fixed in version 1.16.5

**Comment by mattster98** [comment]
One more question, asked here rather than a new issue because it seems super related.  My data is all per-minute, and the data in table form confirms each data point is hh:mm:00 - zero seconds.  The time on the slider is all over the place, in arbitrary increments compared to the data. (including in the original video clip I posted)  Is that just based on the width of the slider and the extents of the data timeframe?  Is that working as intended?

**Comment by andymchugh** [comment]
I believe so. The timeSlider receives the start and end times derived from the min/max of all of the combined timeSeries. If there is no time in the incoming data it falls back on the time range for the dashboard. This min/max sourcing ensures it works correctly with time-offsets where the dashboard range can be very different to the panel range. 

As the timeSlider is moved it produces a normalised 0-1 number and that's combined with the min/max to produce the sample-time. That's then used for display and each of the timeSeries closest datapoint values are displayed or used in the mathjs formulas.

I guess it could having decided what time to display, then look through all the timeSeries to find the closest matching timePoint and then use that as the lookup into all the other timeSeries to choose the closest values. It sounds like all your data always has the same sample time points but that's not a feature of grafana, it's a feature of the data your choosing to combine in the panel.

Maybe that's worthwhile, but it sounds like a fair bit of extra complexity and cpu churn so not convinced it's worth it.
